services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-textile-app
    restart: unless-stopped
    ports:
      - "6060:6060"
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/html/storage/app/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

volumes:
  storage_data:
    driver: local

networks:
  app-network:
    driver: bridge